name: Terraform CI/CD (dev-gcp)

on:
  push:
    branches: [ main ]
    paths: [ 'envs/dev-gcp/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'envs/dev-gcp/**' ]
  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Plan & Apply (dev‑gcp)
    runs-on: ubuntu-latest

    environment: dev-gcp

    container:
      image: kimbodovalcir/kimbodo-posit-actions:latest

    defaults:
      run:
        shell: bash
        working-directory: envs/dev-gcp

    steps:
      - uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

      - name: Authorise git with PAT
        run: |
          git config --global url."https://x-access-token:${{ secrets.GH_PAT_MODULES }}@github.com/".insteadOf "https://github.com/"
     
      - name: Decrypt Terraform SA
        run: |
          sops -d sa.enc.json > /tmp/terraform-sa.json
          echo "Credencial descriptografada em /tmp/terraform-sa.json"

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format & Validate
        run: |
          terraform fmt -check
          terraform validate

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve tfplan
